tag: "dynamics_inpaint"
num_sample: 1
batch_size: 1
sequence: null
pdb_dir: './example/cath1_1b43A02.pdb'
xtc_dir: './example/cath1_1b43A02.xtc'
timestep: 1
num_step: 10
sample_dir: "./sample_dir"
ckpt_dir: "./ckpt_dir"
